services:
  monitoring-provider-alloy:
    profiles:
      - monitoring
    build:
      context: ./alloy
      args:
        - PROVIDER_VERSION=${MONITORING_PROVIDER_ALLOY_IMAGE_VERSION}
    env_file:
      - ./alloy/.env
    volumes:
      - ./alloy/.data:/var/lib/alloy/data
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - ../.provider-logs/:/var/log/ # Adjust the path as needed for your application logs
    depends_on:
      monitoring-provider-tempo:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl -f http://localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  monitoring-provider-grafana:
    profiles:
      - monitoring
    build:
      context: ./grafana
      args:
        - PROVIDER_VERSION=${MONITORING_PROVIDER_GRAFANA_IMAGE_VERSION}
    env_file:
      - ./grafana/.env
    volumes:
      - ./grafana/.data:/var/lib/grafana
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      monitoring-provider-loki:
        condition: service_healthy
      monitoring-provider-alloy:
        condition: service_healthy
      monitoring-provider-mimir:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl -f http://localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  monitoring-provider-loki:
    profiles:
      - monitoring
    build:
      context: ./loki
      args:
        - PROVIDER_VERSION=${MONITORING_PROVIDER_LOKI_IMAGE_VERSION}
    env_file:
      - ./loki/.env
    volumes:
      - ./loki/.data:/loki
      - ./loki/config.yaml:/etc/loki/local-config.yaml
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  monitoring-provider-mimir:
    profiles:
      - monitoring
    build:
      context: ./mimir
      args:
        - PROVIDER_VERSION=${MONITORING_PROVIDER_MIMIR_IMAGE_VERSION}
    env_file:
      - ./mimir/.env
    volumes:
      - ./mimir/config.yml:/etc/config.yml

  monitoring-provider-tempo:
    profiles:
      - monitoring
    build:
      context: ./tempo
      args:
        - PROVIDER_VERSION=${MONITORING_PROVIDER_TEMPO_IMAGE_VERSION}
    env_file:
      - ./tempo/.env
    volumes:
      - ./tempo/config.yml:/etc/config.yml
      - ./tempo/.data:/var/tempo
    healthcheck:
      test: [ "CMD", "curl -f http://localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
